### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by flpms** [pagarme/pagarme-core-api-nodejs#12]
Era esperado que uma empresa do nível do Pagarme tivesse algo tão essencial como essa SDK listada no npm ao invés. Infelizmente parece que a qualidade da empresa tem caído.

**Comment by crossworth** [comment]
Amigo, essa SDK nova do Pagarme tá triste.

Essa SDK ainda tá muito melhor do que a de GO, que nem compilável é atualmente. Inclusive eu acho que é umas das únicas que nem tem exemplo oficial no repo de exemplos https://github.com/pagarme/sdks. Acredito que nem eles conseguiram fazer executar (é um ajuste bem pequeno, mas não entendo como uma empresa do tamanho deles não conseguiu perceber isso ainda).

A parte mais triste de tudo é isso aqui:

![image](https://user-images.githubusercontent.com/1251151/145276569-232e032b-d72d-4537-9e60-40e411fb057e.png)

Eu desconfio que ter swagger spec da API deles seja mais útil do que as SDK's atuais, já que poderíamos pelo menos escolher outros geradores com saídas mais idiomáticas, ou pelo menos compiláveis.

**Comment by lucasnobredev** [comment]
Fala @flpms e @crossworth , tudo bem?

Eu faço parte do time que cuida das SDKs atuais e legadas da Pagar.me/Mundipagg.
Sobre a SDK no npm, todas estão na NPM!

* Pagar.me v5 - [Link](https://www.npmjs.com/package/@pagarme/sdk)
* Pagar.me Legada (v1~v4) - [Link](https://www.npmjs.com/package/pagarme)
* Mundipagg legada - [Link](https://www.npmjs.com/package/mundipagg-nodejs)

A página de SDKs ainda está em construção e percebi que os links dos gerenciadores de cada linguagem não estão lá. Iremos colocar em breve para facilitar.

@crossworth , eu vi somente hoje a sua issue https://github.com/pagarme/pagarme-core-api-go/issues/6 sobre os problemas encontrados na SDK de Go. Desculpe pela demora! :(  

Como você mesmo falou, as nossas SDKs hoje são geradas automaticamente. Vamos lançar em breve uma nova versão desta SDK autogerada, que já deve vir atualizada e seguindo novos padrões de todas as linguagens que o serviço dá suporte! Porém justamente por ela ser autogerada, não conseguimos alterar e aplicar todas as mudanças que você citou na issue. Caso a nova versão que lançaremos ainda sim não atenda o que você comentou, sugiro que faça um fork e siga um projeto mais atualizado. Infelizmente hoje não temos um time dedicado somente a SDKs, ao ponto de aplicar as melhores práticas em cada linguagem. =/

Quaisquer outras dúvidas e sugestões, podem falar aqui ou até mesmo peçam ajuda através do suporte da Pagar.me.

**Comment by flpms** [comment]
Vou abrir outra issue que percebi q está faltando sobre autenticação. Assim ajudar para futura referencia de outros desenvolvedores.
